pipeline {
    agent any

    environment {
        registry = "saifelmasry1/node-project"
        registryCredential = 'my-docker-hub'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'github_UP', url: 'git@github.com:saifelmasry1/nodejs_project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    env.dockerImage = docker.build("${registry}:${BUILD_NUMBER}")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        env.dockerImage.push()
                    }
                }
            }
        }

        stage('Clean Up Local Image') {
            steps {
                script {
                    sh "docker rmi ${registry}:${BUILD_NUMBER} || true"
                }
            }
        }
    }
}
