pipeline {
    agent any

    environment {
        registry = "elmaasry/nodejs_project"  // استخدم اسم الريبو الصحيح على Docker Hub
        registryCredential = 'my-docker-hub'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // بناء صورة Docker باستخدام القيم المحددة
                    env.dockerImage = docker.build("${registry}:${BUILD_NUMBER}")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    // دفع الصورة إلى Docker Hub باستخدام بيانات الاعتماد المحددة
                    docker.withRegistry('', registryCredential) {
                        env.dockerImage.push()
                    }
                }
            }
        }

        stage('Clean Up Local Image') {
            steps {
                script {
                    // تنظيف الصورة المحلية بعد الدفع
                    sh "docker rmi ${registry}:${BUILD_NUMBER} || true"
                }
            }
        }
    }
}
